server:
  port: 8888
#  配置文件，配置端口；注意：yam文件对缩进有要求
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowsync?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #日期格式
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null #null值不带向前端

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml  #mapper.xml文件的位置(可选)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #操作日志，可显示sql语句
